fix: Select correct Superkey/Macro in Layout Editor
Wrong selection could still occur by the following steps:
1) Select a key that does NOT have a Superkey/Macro
2) Assign a Superkey/Macro
3) Click another key which does NOT have a Superkey/Macro assigned.
Error: The Superkey/Macro set on the previous key is still selected.

Maybe related to: https://github.com/radix-ui/primitives/issues/3089

Signed-off-by: Lawrence Brooks <84.lbrooks@gmail.com>